# Generated by Django 3.1.2 on 2020-11-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=200)),
                ('FEmailID', models.EmailField(max_length=200)),
                ('FPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName', models.CharField(max_length=200)),
                ('SubFaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.BigIntegerField()),
                ('SName', models.CharField(max_length=200)),
                ('SClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.class')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('SClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.class')),
                ('SFaculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.faculties')),
                ('SSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
                ('SWeek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.week')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='ClassFaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculties'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Attend', models.BooleanField(default=False)),
                ('AClassName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.class')),
                ('AFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.faculties')),
                ('ASID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students')),
                ('AStartTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.schedule')),
                ('ASubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
            ],
        ),
    ]
