# Generated by Django 3.1.2 on 2020-11-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201111_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='AClassName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='AFID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.faculties'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ASID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.students'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='AStartTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.schedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ASubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassFaculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.faculties'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='SSubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='SWeek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.week'),
        ),
        migrations.AlterField(
            model_name='students',
            name='SClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='SubFaculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.faculties'),
        ),
    ]
