# Generated by Django 3.1.2 on 2020-11-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201111_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
