# Generated by Django 3.1.2 on 2020-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201128_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
