# Generated by Django 3.1.2 on 2020-11-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_attendimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='img',
        ),
    ]
