# Generated by Django 3.1.2 on 2020-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_attendance_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendimages',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
