# Generated by Django 3.1.1 on 2020-10-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rollNo',
        ),
    ]
